### ISSUE TITLE
No visible @interface for 'UIBezierPath' declares the selector 'rg_drawLinearGradient:locations:colors:drawType:'

### ISSUE THREAD

**Issue by Mempz** [RengeRenge/RGImagePicker#2]
undeclared selector at RGImagePickerCell.m

![image](https://user-images.githubusercontent.com/20332590/70019173-607f8f80-15c3-11ea-96a6-3d92e5e03bc3.png)

**Comment by RengeRenge** [comment]
> undeclared selector at RGImagePickerCell.m
> 
> ![image](https://user-images.githubusercontent.com/20332590/70019173-607f8f80-15c3-11ea-96a6-3d92e5e03bc3.png)
@Mempz

Sorry, there are some unsynchronized code for 'RGUIKit'.
I have fixed it.
Please update version to 1.0.3.
`pod update RGImagePicker`
