### ISSUE TITLE
Crash when playing slomo videos using the picker

### ISSUE THREAD

**Issue by Mempz** [RengeRenge/RGImagePicker#3]
RGImagePicker.m
![image](https://user-images.githubusercontent.com/20332590/74127593-ff54e780-4c15-11ea-8657-736c50154752.png)

**Comment by RengeRenge** [comment]
> RGImagePicker.m
> ![image](https://user-images.githubusercontent.com/20332590/74127593-ff54e780-4c15-11ea-8657-736c50154752.png)

Thank you for your issue, I have fixed the bug.
Please update version to 1.0.4

**Comment by Mempz** [comment]
Thank you! 👍
